version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
    environment:
      MONGODB_DATABASE: demo
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017

      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/mongodb/data:/data/db
    ports:
      - 27017:27017
    restart: always

  redis:
    image: 'redis:latest'
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
